/**
 * Creating a sidebar enables you to:
 - create an ordered group of docs
 - render a sidebar for each doc of that group
 - provide next/previous navigation

 The sidebars can be generated from the filesystem, or explicitly defined here.

 Create as many sidebars as you want.
 */

// @ts-check

/** @type {import('@docusaurus/plugin-content-docs').SidebarsConfig} */
const sidebars = {
    backend: [
        'backend',
        {
            type: 'autogenerated',
            dirName: 'backend',
        }
    ],
    devops: [
        'devops',
        {
            type: 'category',
            label: 'Docker',
            items: [{
                type: 'autogenerated',
                dirName: 'devops/docker',
            }],
        },
        {
            type: 'category',
            label: 'Deploy',
            items: [{
                type: 'autogenerated',
                dirName: 'devops/deploy',
            }],
        },
    ],
    frontend: [
        'frontend',
        {
            type: 'autogenerated',
            dirName: 'frontend',
        },
    ],
    git: [
        'git'
    ],
    pet_project: [
        'pet-project',
        {
            type: 'autogenerated',
            dirName: 'pet-project',
        }
    ],
};

module.exports = sidebars;
